apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: inamk-1
  name: inamk-1
  namespace: example
spec:
  initContainers:
  - name: wait
    image: busybox
    command: ['sh', '-c', 'sleep 5']
  containers:
  - image: nginx
    name: inamk-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
